# Generated by Django 5.2.6 on 2025-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='mandatory_document_types',
            field=models.ManyToManyField(blank=True, related_name='mandating_clinics', to='documents.documenttype', verbose_name='Tipos de Documentos Obrigatórios'),
        ),
    ]
