version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9090:9000"
      - "9091:9001"

  web:
    build: ./djangoapp
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    
    env_file:
      - .env
      
    volumes:
      - ./djangoapp:/app
      
    ports:
      - "8001:8000"
      
    depends_on:
      - db
      - minio

volumes:
  pg_data:
  minio_data: