# Generated by Django 5.2.6 on 2025-09-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('dialysis', '0001_initial'),
        ('organization', '0001_initial'),
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='guide_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameters.guidetype', verbose_name='Tipo de Guia'),
        ),
        migrations.AddField(
            model_name='guide',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guides', to='dialysis.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='guide',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parameters.procedurestatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='payer',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='payers', to='organization.clinic', verbose_name='Clínicas Atendidas'),
        ),
        migrations.AddField(
            model_name='guide',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guides', to='billing.payer', verbose_name='Convênio'),
        ),
    ]
