# Generated by Django 5.2.6 on 2025-09-05 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Guia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Guia',
                'verbose_name_plural': 'Tipos de Guias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Status')),
                ('slug', models.SlugField(help_text='Identificador único para uso interno no código (ex: DRAFT, APPROVED). Não altere após a criação.', max_length=100, unique=True, verbose_name='Identificador (slug)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Status de Procedimento',
                'verbose_name_plural': 'Status de Procedimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParameterRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('PATIENT', 'Cadastro de Paciente'), ('GUIDE', 'Guia de Faturamento')], default='GUIDE', max_length=10, verbose_name='Contexto')),
                ('nature', models.CharField(blank=True, choices=[('CHRONIC', 'Crônico'), ('ACUTE', 'Agudo')], max_length=10, verbose_name='Natureza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Regra Ativa')),
                ('guide_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.guidetype', verbose_name='Tipo de Guia')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_rules', to='billing.payer', verbose_name='Convênio')),
                ('required_documents', models.ManyToManyField(to='documents.documenttype', verbose_name='Tipos de Documentos Exigidos')),
            ],
            options={
                'verbose_name': 'Regra de Parâmetro',
                'verbose_name_plural': 'Regras de Parâmetros',
                'ordering': ['payer', 'context', 'guide_type'],
            },
        ),
    ]
