# Generated by Django 5.2.5 on 2025-09-04 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('PATIENT', 'Cadastro de Paciente'), ('GUIDE', 'Guia de Faturamento')], default='GUIDE', max_length=10, verbose_name='Contexto')),
                ('guide_type', models.CharField(blank=True, choices=[('APAC', 'APAC'), ('SADT', 'Guia SADT'), ('CONSULTA', 'Consulta'), ('INTERNACAO', 'Internação')], max_length=16, verbose_name='Tipo de Guia')),
                ('nature', models.CharField(blank=True, choices=[('CHRONIC', 'Crônico'), ('ACUTE', 'Agudo')], max_length=10, verbose_name='Natureza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Regra Ativa')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_rules', to='billing.payer', verbose_name='Pagador')),
                ('required_documents', models.ManyToManyField(to='documents.documenttype', verbose_name='Tipos de Documentos Exigidos')),
            ],
            options={
                'verbose_name': 'Regra de Parâmetro',
                'verbose_name_plural': 'Regras de Parâmetros',
                'ordering': ['payer', 'context', 'guide_type'],
            },
        ),
    ]
