# Generated by Django 5.2.5 on 2025-09-03 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(verbose_name='ID do Objeto Pai')),
                ('type', models.CharField(choices=[('ID', 'Documento de Identidade'), ('CPF', 'Cadastro de Pessoa Física (CPF)'), ('CNS', 'Cartão Nacional de Saúde (CNS)'), ('COMP_RES', 'Comprovante de Residência'), ('CONSENT', 'Termo de Consentimento'), ('LAUDO', 'Laudo Nefrológico'), ('EXAME', 'Exame Laboratorial'), ('PRESC', 'Prescrição'), ('SESS', 'Folha de Sessão'), ('OUTRO', 'Outro')], max_length=16, verbose_name='Tipo do Documento')),
                ('file', models.FileField(upload_to='raw/%Y/%m/%d/', verbose_name='Arquivo')),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organization.clinic', verbose_name='Clínica')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo do Objeto Pai')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx')],
            },
        ),
    ]
