# Generated by Django 5.2.6 on 2025-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, help_text='Descrição customizada para o documento, usada para documentos opcionais/outros.', max_length=255, verbose_name='Descrição'),
        ),
    ]
