# Generated by Django 5.2.5 on 2025-09-04 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(help_text='Formato: 123.456.789-00', max_length=14, unique=True, verbose_name='CPF')),
                ('cns', models.CharField(max_length=18, unique=True, verbose_name='Cartão Nacional de Saúde (CNS)')),
                ('cid_principal', models.CharField(blank=True, help_text='Código da Classificação Internacional de Doenças', max_length=10, verbose_name='CID Principal')),
                ('patient_type', models.CharField(choices=[('CHRONIC', 'Crônico'), ('ACUTE', 'Agudo')], default='CHRONIC', max_length=10, verbose_name='Tipo (Crônico/Agudo)')),
                ('status', models.CharField(choices=[('IN_TREATMENT', 'Em Tratamento'), ('DISCHARGED', 'Alta Ambulatorial'), ('DECEASED', 'Óbito'), ('TRANSFERRED', 'Transferido')], default='IN_TREATMENT', max_length=16, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o paciente está ativo no sistema. É desmarcado automaticamente para status de alta, óbito ou transferência.', verbose_name='Cadastro Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='organization.clinic', verbose_name='Clínica')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='billing.payer', verbose_name='Pagador (Convênio)')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['full_name'],
            },
        ),
    ]
