# Generated by Django 5.2.5 on 2025-09-04 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Convênio')),
                ('payer_type', models.CharField(choices=[('SUS', 'SUS'), ('PRIVATE', 'Convênio Privado')], default='PRIVATE', max_length=10, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guide_type', models.CharField(choices=[('APAC', 'APAC'), ('SADT', 'Guia SADT'), ('CONSULTA', 'Consulta'), ('INTERNACAO', 'Internação')], max_length=16, verbose_name='Tipo de Guia')),
                ('nature', models.CharField(choices=[('CHRONIC', 'Crônico'), ('ACUTE', 'Agudo')], max_length=10, verbose_name='Natureza (Crônico/Agudo)')),
                ('authorization_number', models.CharField(blank=True, max_length=50, verbose_name='Número da Autorização/Guia')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_REVIEW', 'Em Auditoria'), ('APPROVED', 'Aprovada'), ('BILLED', 'Faturada'), ('DENIED', 'Glosada')], default='DRAFT', max_length=16, verbose_name='Status')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Vigência (Início)')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Vigência (Fim)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guides', to='organization.clinic', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
                'ordering': ['-created_at'],
            },
        ),
    ]
