# Generated by Django 5.2.5 on 2025-09-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('dialysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guides', to='dialysis.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='guide',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guides', to='billing.payer', verbose_name='Pagador (Convênio)'),
        ),
    ]
