# Generated by Django 5.2.6 on 2025-09-09 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Aprovado'), ('REJECTED', 'Recusado com Pendência')], max_length=16, verbose_name='Decisão')),
                ('comments', models.TextField(blank=True, verbose_name='Comentários/Justificativa')),
                ('audited_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Auditoria')),
                ('payload_hash', models.CharField(editable=False, help_text='Hash SHA-256 do estado da guia e seus documentos no momento da auditoria.', max_length=64, verbose_name='Hash da Carga Probatória (Assinatura)')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits_performed', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
            ],
            options={
                'verbose_name': 'Decisão de Auditoria',
                'verbose_name_plural': 'Decisões de Auditoria',
                'ordering': ['-audited_at'],
            },
        ),
    ]
