# Generated by Django 5.2.5 on 2025-09-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdecision',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_decisions', to='billing.guide', verbose_name='Guia Auditada'),
        ),
    ]
